INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/roulette2, TIME:2025-04-27 19:07:02.862378, CODE:404
INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/roulette, TIME:2025-04-27 19:08:04.500093, CODE:200
INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/phaser-game/src/casino/scenes/Roulette.js, TIME:2025-04-27 19:08:04.652912, CODE:200
INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/phaser-game/phaser.js, TIME:2025-04-27 19:08:04.661270, CODE:200
INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/phaser-game/src/gameObjects/CoinCounter.js, TIME:2025-04-27 19:08:04.860821, CODE:200
INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/phaser-game/assets/roulette/roulette_bg_2.png, TIME:2025-04-27 19:08:06.237049, CODE:200
INFO:src.init:	METHOD:GET, USERNAME:t, IP:172.19.0.1, PATH:/phaser-game/assets/roulette/roulette_wheel.png, TIME:2025-04-27 19:08:06.253887, CODE:200
INFO:src.init:Wager amount: 0
INFO:src.init:bet_type: 3rd Twelve
INFO:src.init:username: t
ERROR:src.init:Exception on /phaser/playRoulette [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/src/phaser_routes.py", line 145, in roulette_request
    data = {"user_cashout": user_cashout_dict[username], "outcome": outcome}
KeyError: 't'
INFO:src.init:	METHOD:POST, USERNAME:t, IP:172.19.0.1, PATH:/phaser/playRoulette, TIME:2025-04-27 19:08:14.610018, CODE:500
